(define (closer-city lat lon city-a city-b)
    (define new-city (make-city 'new_city lat lon))
    (define distance_a (distance city-a new_city))
    (define distance_b (distance city-b new_city))
    (if (< distance_a distance_b)
        (get-name city-a)
        (get-name city-a)
    )
)
